modLoader="neoforge"
loaderVersion="[21,)"
license="MIT"
showAsResourcePack=false
updateJSONURL=""
mixin="variantgenerator.mixins.json"

[[mods]]
modId="variantgenerator"
version="${file.jarVersion}"
displayName="Variant Generator"
logoFile="assets/variantgenerator/icon.png"
credits="Variant Generator Development Team"
authors="Developer"
description="""
Automatically generates netherite and enderite variants for items from other mods.
Uses mixins to extract colors and stats from the Enderite mod.
Scans for iron variants, colorizes textures, generates recipes, and balances stats.
"""

[[dependencies.variantgenerator]]
    modId="neoforge"
    mandatory=true
    versionRange="[21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.variantgenerator]]
    modId="architectury"
    mandatory=true
    versionRange="[15.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.variantgenerator]]
    modId="enderitemod"
    mandatory=true
    versionRange="[1.7.0,)"
    ordering="NONE"
    side="BOTH"
